# Chapter.02 파이썬과 주피터 노트북 기초

## 2.3.7 클래스와 인스턴트

### 클래스
    : 데이터의 구조와 계산로직을 함께 묶어둔 목록
        보통 다른 사람이 만들어둔 클래스 사용한다.

In [1]:
#< 클래스 만들어보기 >

#class 클래스명 :
#    def 함수명1(인수) :
#        함수명1의 처리
        
#    def 함수명2(인수):
#        함수명2의 처리

In [4]:
class Sample_Class :
    def __init__(self, data1, data2) :
        self.data1 = data1
        self.data2 = data2
        
    def method2(self) :
        return(self.data1 + self.data2)

###  인스턴스
        : 데이터를 저장하는 것

In [5]:
# 인스턴스 생성해보기

sample_instance = Sample_Class(data1 = 2, data2 = 3)

In [6]:
# 점(.)기호 : 인스턴스 안의 데이터 꺼내기

sample_instance.data1

2

In [8]:
# 클래스의 함수 사용하는 경우도 마찬가지 !

sample_instance.method2()

5

## 2.3.8 if문을 사용한 분기

### if문 : 만약 ~한다면 ~ 동작을 한다

In [10]:
#if(조건) :
    # 조건을 만족할 경우의 동작
#else :
    # 조건을 만족하지 않을 경우의 동작

In [11]:
data = 1
if(data<2) :
    print("2보다 작은 데이터입니다.")
else :
    print("2이상인 데이터입니다.")

2보다 작은 데이터입니다.


In [12]:
# 조건 만족하지 않을 때

data = 3
if(data<2) :
    print("2보다 작은 데이터입니다.")
else :
    print("2이상인 데이터입니다.")

2이상인 데이터입니다.


## 2.3.9 for문을 사용한 반복 실행

### for문 :
    같은 계산을 몇 번이고 반복해서 수행하는 경우

In [13]:
#  range 함수 : 횟수 지정

range(0,3)

range(0, 3)

In [14]:
for i in range(0, 3) :
    print(i)

0
1
2


In [15]:
for i in range(0,3) :
    print("hello")

hello
hello
hello


## 2.4.1 분석을 위한 추가 기능 설치

In [16]:
# numpy : 배열 데이터를 다루는 클래스를 주로 사용. 행열 연산에 강한 패키지이다.
# pandas : 데이터프레임이라는 데이터 관리에 무척 강력한 클래스를 주로 사용.

import numpy as np
import pandas as pd

## 2.4.3 리스트

In [18]:
# 리스트 : 복수의 데이터를 모아서 묶어둔 것. 파이썬의 표준 데이터 형식
    # 대괄호 []로 감싸준다.
 
sample_list = [1, 2, 3, 4, 5]
sample_list

[1, 2, 3, 4, 5]

## 2.4.4 행과 열

### 행(Row)은 가로, 열(Col)은 세로
    행 번호 -> 열 번호 순서로 표기

## 2.4.5 배열

In [19]:
# numpy 배열 사용하기

sample_array = np.array([1, 2, 3, 4, 5])
sample_array

array([1, 2, 3, 4, 5])

In [23]:
# ! 배열을 대상으로 하는 연산은 배열 내부 데이터 모두에 적용된다
sample_array + 2

array([3, 4, 5, 6, 7])

In [24]:
sample_array * 2

array([ 2,  4,  6,  8, 10])

In [25]:
# 하나의 배열에는 동일한 데이터형만 들어갈 수 있다.
# 문자 숫자 동시에 배열하면 모두 문자열로 취급된다.
np.array([1, 2, "A"])

array(['1', '2', 'A'], dtype='<U21')

In [26]:
# 2차원 배열 만들기 : 리스트 중첩하여 인수로 넘긴다.
 
sample_array_2 = np.array(
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10]])
sample_array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
# shape : 행, 열 수 확인

sample_array_2.shape

(2, 5)

## 2.4.6 등차수열을 만드는 방법

### 등차수열 : 앞뒤 값의 차이가 동일한 수열

In [28]:
# 등차수열 만들기 : np.arange 함수
    # 시작 위치 : start, 종료위치 : stop, 차잇값 : step
    # stop으로 지정한 값은 배열에 포함되지 않는다.

np.arange(start = 1, stop = 6, step = 1)

array([1, 2, 3, 4, 5])

In [29]:
np.arange(start = 0.1, stop = 0.8, step = 0.2)

array([0.1, 0.3, 0.5, 0.7])

## 2.4.7 여러가지 배열을 만드는 방법

### np.tile 함수 : 같은 값을 잔뜩 채운 배열

In [31]:
np.tile("A", 5)

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [32]:
np.tile(0, 5)

array([0, 0, 0, 0, 0])

In [33]:
# 모두 0인 배열을 만들때는 np.zeros 함수 사용

np.zeros(4)

array([0., 0., 0., 0.])

In [34]:
# np.zeros로 2차원 배열 만들기

np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
# np.ones : 1로만 된 배열 만들기

np.ones(3)

array([1., 1., 1.])

## 2.4.8 슬라이싱

### 슬라이싱 : numpy 배열과 리스트에 작업 할 수있다.
    -> 간단히 데이터 추출할 수 있다.

In [36]:
d1_array = np.array([1, 2, 3, 4, 5])
d1_array

array([1, 2, 3, 4, 5])

In [37]:
# 데이터를 꺼낼때는 대괄호를 사용한다.
d1_array[0]

1

In [38]:
# 콜론(:) 사용  : 범위를 지정해서 데이터 꺼낼 때

d1_array[1:3]

array([2, 3])

In [39]:
# 2차원 이상의 배열에 대해서도 슬라이싱하기

d2_array = np.array(
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10]])
d2_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
# 1행의 4열의 데이터 가져와
d2_array[0,3]

4

In [41]:
d2_array[1, 2:4]

array([8, 9])

In [45]:
 sample_df = pd.DataFrame({
     'col1' : sample_array,
     'col2' : sample_array * 2,
     'col3' : ["A", "B", "C", "D", "E"]
 })
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [46]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

## 2.4.10 파일을 읽어 들이는 방법

 데이터를_저장할_변수명 = pd.read_csv("파일명")

In [47]:
file_data = pd.read_csv("/Users/seuli/Desktop/개발자/통계학 source/sample/2-4-1-sample_data.csv")
print(file_data)

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


## 2.4.11 데이터프레임 병합

In [50]:
df_1 = pd.DataFrame({
     'col1' : np.array([1, 2, 3]),
     'col2' : np.array(["A", "B", "C"])
 })
df_2 = pd.DataFrame({
     'col1' : np.array([4, 5, 6]),
     'col2' : np.array(["D", "E", "F"])
 })

In [51]:
print(pd.concat([df_1, df_2]))

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [53]:
# 세로방향(행방향)으로 이어 붙이기
# pd.concat 함수 사용(axis=0)

print(pd.concat([df_1, df_2]))

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [54]:
# 가로방향으로 이어붙이기 -> axis = 1

print(pd.concat([df_1, df_2], axis=1))

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F


## 2.4.12 데이터프레임 열에 대해 작업하기

In [55]:
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [56]:
# 점(.) 사용 : 열 이름 지정하여 호출

print(sample_df.col2)

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64


In [57]:
# 대괄호 이용하는 방법도 있다.

print(sample_df["col2"])

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64


In [58]:
print(sample_df[["col2"]])

   col2
0     2
1     4
2     6
3     8
4    10


In [60]:
# 복수의 열 추출

print(sample_df[["col2", "col3"]])

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


In [61]:
# 지정한 열만 빼고 데이터 추출
print(sample_df.drop("col1", axis=1))

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


## 2.4.13 데이터프레임 행에 대해 작업하기

In [62]:
print(sample_df.head(n=3))

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C


In [63]:
# query 함수 : 여러가지 조건을 지정해서 데이터를 꺼내오는게 가능
print(sample_df.query('index==0'))

   col1  col2 col3
0     1     2    A


In [64]:
   # col3열에서 값인 A인 행만 꺼내기

print(sample_df.query('col3=="A"'))

   col1  col2 col3
0     1     2    A


In [65]:
# 복수의 조건 지정
    # | : 또는 or 조건

print(sample_df.query('col3 == "A" | col3 == "D" '))

   col1  col2 col3
0     1     2    A
3     4     8    D


In [66]:
    # & : 그리고 조건, AND 조건

print(sample_df.query('col3 == "A" & col1 == 3'))

Empty DataFrame
Columns: [col1, col2, col3]
Index: []


In [67]:
# 행과 열 모두에 조건 지정

print(sample_df.query('col3 == "A"')[["col2", "col3"]])

   col2 col3
0     2    A


## 2.4.14 시리즈

In [68]:
type(sample_df)

pandas.core.frame.DataFrame

In [69]:
type(sample_df.col1)

pandas.core.series.Series

In [70]:
# 시리즈는 배열과 비슷한 작업을 할 수 있지만, 배열쪽이 좀 더 사용하기 쉽다.
# 시리즈를 배열로 변환하려면 np.array 인수로 시리즈형 변수 넘기면 된다.

type(np.array(sample_df.col1))

numpy.ndarray

In [71]:
# 시리즈형 변수에서 다시 한 번 .value 변수를 꺼내면 배열이 추출된다.
type(sample_df.col1.values)

numpy.ndarray

## 2.4.15 함수의 도움말

함수의 사용법을 알고자 할때 : help 함수

In [72]:
help(sample_df.query)

Help on method query in module pandas.core.frame:

query(expr, inplace=False, **kwargs) method of pandas.core.frame.DataFrame instance
    Query the columns of a DataFrame with a boolean expression.
    
    Parameters
    ----------
    expr : string
        The query string to evaluate.  You can refer to variables
        in the environment by prefixing them with an '@' character like
        ``@a + b``.
    inplace : bool
        Whether the query should modify the data in place or return
        a modified copy
    
        .. versionadded:: 0.18.0
    
    kwargs : dict
        See the documentation for :func:`pandas.eval` for complete details
        on the keyword arguments accepted by :meth:`DataFrame.query`.
    
    Returns
    -------
    q : DataFrame
    
    See Also
    --------
    pandas.eval
    DataFrame.eval
    
    Notes
    -----
    The result of the evaluation of this expression is first passed to
    :attr:`DataFrame.loc` and if that fails because of a
    mul